# Generated by Django 3.2 on 2021-04-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_type', models.CharField(max_length=250)),
                ('product_desc', models.TextField()),
                ('Product_image', models.CharField(max_length=1000)),
            ],
        ),
    ]
